### PR TITLE
Bump gitpython dev dep

### PR DESCRIPTION
**Pull request by rocodes**
## Status

Ready for review

## Description of Changes

- Bump dev dependencies (specifically gitpython) in main and launcher environments

## Testing

- CI passes; `make test` with launcher venv activated passes
- visual review makes sense 

## Deployment

n/a 

## Checklist

n/a

### CODE REVIEW

**Review by cfm — COMMENTED** [review]
@rocodes, since these are just development dependencies—and everything appears to work!—this should be good to go with rubber-stamping.

However, the noisy diff is confusing to me, even ignoring things like line-endings and automatic comments.  Is this the result of running `make update-pip-requirements` with no changes to either `dev-requirements.in` file, rather than pinning a new version or range of `gitpython` there?  I *can't* run that command to verify it; I get:

```sh-session
(.venv) user@sd-dev:~/securedrop-workstation/launcher$ make update-pip-requirements
pip-compile --allow-unsafe --generate-hashes --output-file=dev-requirements.txt dev-requirements.in
Traceback (most recent call last):
  File "/home/user/securedrop-workstation/launcher/.venv/bin/pip-compile", line 5, in <module>
    from piptools.scripts.compile import cli
  File "/home/user/securedrop-workstation/launcher/.venv/lib/python3.9/site-packages/piptools/scripts/compile.py", line 21, in <module>
    from ..repositories import LocalRequirementsRepository, PyPIRepository
  File "/home/user/securedrop-workstation/launcher/.venv/lib/python3.9/site-packages/piptools/repositories/__init__.py", line 1, in <module>
    from .local import LocalRequirementsRepository
  File "/home/user/securedrop-workstation/launcher/.venv/lib/python3.9/site-packages/piptools/repositories/local.py", line 14, in <module>
    from .pypi import PyPIRepository
  File "/home/user/securedrop-workstation/launcher/.venv/lib/python3.9/site-packages/piptools/repositories/pypi.py", line 22, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
ImportError: cannot import name 'BAR_TYPES' from 'pip._internal.cli.progress_bars' (/home/user/securedrop-workstation/launcher/.venv/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py)
make: *** [Makefile:3: update-pip-requirements] Error 1
```

This is resolvable with:

```sh-session
(.venv) user@sd-dev:~/securedrop-workstation/launcher$ pip install --upgrade pip-tools
[...]
Installing collected packages: pip-tools
  Attempting uninstall: pip-tools
    Found existing installation: pip-tools 6.4.0
    Uninstalling pip-tools-6.4.0:
      Successfully uninstalled pip-tools-6.4.0
Successfully installed pip-tools-7.3.0
```

Then I can do and get:

```sh-session
(.venv) user@sd-dev:~/securedrop-workstation/launcher$ make update-pip-requirements
[...]
(.venv) user@sd-dev:~/securedrop-workstation/launcher$ git diff
diff --git a/launcher/dev-requirements.txt b/launcher/dev-requirements.txt
index 95dfc43..95059ea 100644
--- a/launcher/dev-requirements.txt
+++ b/launcher/dev-requirements.txt
@@ -1,6 +1,6 @@
 #
-# This file is autogenerated by pip-compile with python 3.9
-# To update, run:
+# This file is autogenerated by pip-compile with Python 3.9
+# by the following command:
 #
 #    pip-compile --allow-unsafe --generate-hashes --output-file=dev-requirements.txt dev-requirements.in
 #
```

So I'm happy with the actual diff here; I'm just puzzled by how it came about.

**Comment by rocodes** [comment]
That's very fair.  I was not sure how to update a transitive dependency without adding it to dev-requirements.in either, but I manually updated it on my own machine with `pip install --upgrade gitpython`, removed the hash in requirements.txt, and recompiled using pip compile to pull in the updated version.  Now that I say it 'out loud', it seems hacky doesn't it.

**Comment by rocodes** [comment]
Let's not merge it as is, I'll clean it up tomorrow and send it back your way. Sorry for the back and forth.

**Comment by cfm** [comment]
No problem.  :-)  How would you feel about *making* it explicit in `dev-requirements.in`, as in <https://github.com/freedomofpress/securedrop-client/blob/38aa87d13b5b400e7ea1f682a12f90747f47f0fb/requirements/dev-sdw-requirements.in#L9>?  That way the `.in` and the `.txt` stay in sync, in that direction, with the former supplying the "why" and the latter the "what".

**Comment by rocodes** [comment]
So..... :upside_down_face: 

I realized that we haven't officially talked about using python3.9 in the repo, so I rebuilt my venv using python 3.8, added gitpython to the *.in files, and ran `make update-pip-requirements`.  It's still noisy.

**Review by cfm — APPROVED** [review]
Still noisy, but the noise all makes sense now.  Thanks, @rocodes!
